### ISSUE TITLE
Meetup checklist

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/ds-incubator#27]
I use this checklist to guide myself through the process of developing and running a ds-incubator meetup. It is meant to be copy-pasted into the issue associated to each specific meetup. If you find it useful please share your feedback to help me develop a simpler, more general version.

```
### 2h before

- [ ] Open meetup issue, paste this template and edit as necessary
- [ ] Link resources
- [ ] Develop content for the ds-incubator website
- [ ] Announce on #coding
- [ ] Add meetup date, title and link to the invitation on 2dii's calendar
- [ ] Set alarm for +15' into the meeting
- [ ] Set alarm for +25' into the meeting

### 10' before

- [ ] Remind meeting and share link on #coding
- [ ] Login at <https://zoom.us/> and start recurring ds-incubator meeting`***`
    * `***` Backup (Google) https://meet.google.com/azf-xifn-scd
- [ ] Under _Participants > More_ uncheck "Put participants in waiting room ..."

### Start

- [ ] 00': Welcome
- [ ] 02': Announcements
- [ ] 05': Record
- [ ] 15': Q&A + discuss "must-have" or "nice-to-have"
- [ ] 25': End
- [ ] 30': Upload video
- [ ] 35': Link video under resources
- [ ] 35': Label as "must-have" or "nice-to-have"
```

**Comment by maurolepore** [comment]
I moved this to .github/ISSUE_TEMPLATE
